/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as RequestRouteImport } from './routes/request'
import { Route as PhotoGuideRouteImport } from './routes/photo-guide'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'
import { Route as ApiPhotosKeyRouteImport } from './routes/api.photos.$key'

const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoGuideRoute = PhotoGuideRouteImport.update({
  id: '/photo-guide',
  path: '/photo-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPhotosKeyRoute = ApiPhotosKeyRouteImport.update({
  id: '/api/photos/$key',
  path: '/api/photos/$key',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/gallery': typeof GalleryRoute
  '/photo-guide': typeof PhotoGuideRoute
  '/request': typeof RequestRoute
  '/volunteer': typeof VolunteerRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/photos/$key': typeof ApiPhotosKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/gallery': typeof GalleryRoute
  '/photo-guide': typeof PhotoGuideRoute
  '/request': typeof RequestRoute
  '/volunteer': typeof VolunteerRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/photos/$key': typeof ApiPhotosKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/gallery': typeof GalleryRoute
  '/photo-guide': typeof PhotoGuideRoute
  '/request': typeof RequestRoute
  '/volunteer': typeof VolunteerRoute
  '/admin_/login': typeof AdminLoginRoute
  '/api/photos/$key': typeof ApiPhotosKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/gallery'
    | '/photo-guide'
    | '/request'
    | '/volunteer'
    | '/admin/login'
    | '/api/photos/$key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/gallery'
    | '/photo-guide'
    | '/request'
    | '/volunteer'
    | '/admin/login'
    | '/api/photos/$key'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/gallery'
    | '/photo-guide'
    | '/request'
    | '/volunteer'
    | '/admin_/login'
    | '/api/photos/$key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  GalleryRoute: typeof GalleryRoute
  PhotoGuideRoute: typeof PhotoGuideRoute
  RequestRoute: typeof RequestRoute
  VolunteerRoute: typeof VolunteerRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ApiPhotosKeyRoute: typeof ApiPhotosKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photo-guide': {
      id: '/photo-guide'
      path: '/photo-guide'
      fullPath: '/photo-guide'
      preLoaderRoute: typeof PhotoGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/photos/$key': {
      id: '/api/photos/$key'
      path: '/api/photos/$key'
      fullPath: '/api/photos/$key'
      preLoaderRoute: typeof ApiPhotosKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  GalleryRoute: GalleryRoute,
  PhotoGuideRoute: PhotoGuideRoute,
  RequestRoute: RequestRoute,
  VolunteerRoute: VolunteerRoute,
  AdminLoginRoute: AdminLoginRoute,
  ApiPhotosKeyRoute: ApiPhotosKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
